### ISSUE TITLE
floret vectors not used 

### ISSUE THREAD

**Issue by birolkuyumcu** [aajanki/floret-finnish#1]
evaluation  codes not use .floret file 
so how to compare ?

**Comment by aajanki** [comment]
You need to train the Floret model yourself to generate the .bin and .vec files needed in the evaluations. See the [training section](https://github.com/aajanki/floret-finnish#training-a-finnish-floret-model) on the readme for instructions.

**Comment by birolkuyumcu** [comment]
you compare fasttext and floret and
compare  model file sizes
<html><body>


fastText (.bin) | 6.8 GB
-- | --
floret (.floret) | 0.1 GB


</body>
</html>

But  you dont use  .floret file so comparision is not correct 
for fair comparision 

use .floret   file  
if you dont 
write floret  trained .bin an vec file size table
